### PR TITLE
As there hasn't been any activity over the past month on this repository, I forked it to fix some issues and implement the features I needed

### PR DESCRIPTION
**Pull request by racodond**
As there hasn't been any activity over the past month on this repository, I forked it to fix some issues and implement the features I needed:
 * https://github.com/AmadeusITGroup/sonar-stash/commit/4c0f92861349704782f070390020bd4905992266 fixes https://github.com/AmadeusITGroup/sonar-stash/issues/25 (Comment "xxx" cannot be pushed to Stash like it does not belong to diff view)
 * https://github.com/AmadeusITGroup/sonar-stash/commit/2742d30de25bc04ee2b5ae2679a2b46c5b955680 implements https://github.com/AmadeusITGroup/sonar-stash/pull/20 (Make summary comment optional) + https://github.com/AmadeusITGroup/sonar-stash/commit/ccb6b80e7fd58e094b28de4a9dba42326bbbbe7d adds the ability to display a tiny summary while hiding the overview for the developer to be notified when the incremental analysis has been performed.
 * I also did some cleanup in terms of line endings, formatting, etc. to ease future contributions

Tell me if you're interested in merging this contribution or if I shall keep adding my new features on my fork.

### CODE REVIEW

**Comment by acopet** [comment]
Hello David,

For your information, we are working on next plugin version (1.1.0) which will integrates mainly issues #11 and #14. This version will be release at the beginning of next year but both features should be available before Xmas on master branch.

We have not planned to integrate #20 in release 1.1.0 but it could be a candidate for next version. Nevertheless, we are interested by your fix on #25 for version 1.1.0: could it be possible to open a dedicated pull-request with only this change?

Cheers,
Antoine

**Comment by acopet** [comment]
Hello David,

For your information, we are working on next plugin version (1.1.0) which will integrates mainly issues #11 and #14. This version will be release at the beginning of next year but both features should be available before Xmas on master branch.

We have not planned to integrate #20 in release 1.1.0 but it could be a candidate for next version. Nevertheless, we are interested by your fix on #25 for version 1.1.0: could it be possible to open a dedicated pull-request with only this change?

Cheers,
Antoine

**Comment by racodond** [comment]
Hi,

You can cherry pick https://github.com/racodond/sonar-stash/commit/4c0f92861349704782f070390020bd4905992266

Regards,

David

**Comment by acopet** [comment]
This pull-request can be closed: we will open dedicated Pull-requests to integrate #20 and #25.

**Comment by re-schneider** [comment]
Linked to Pull-resquest #24

**Pull request closed without merging**
