### PR TITLE
Code coverage evolution inside the pull-request

### PR DESCRIPTION
**Pull request by acopet**
Linked to #70.

### CODE REVIEW

**Comment by t-8ch** [comment]
Some remarks:
* Unit tests are failing, this seems to be a difference between Java 7 and 8.
* Should SonarQube not create the issues itself? (https://sonarqube.com/coding_rules#rule_key=common-java:InsufficientLineCoverage)
* Can we use `SensorContext.getMeasure(CoreMetrics.{NEW_}LINE_COVERAGE)` for the projectwide metrics?

**Comment by acopet** [comment]
Hi @t-8ch,

- Your comments about Unit test failing and SensorContext.getMeasure(CoreMetrics.{NEW_}LINE_COVERAGE) have been integrated.
- About InsufficientLineCoverage rule, not sure it is the expected issue to be used. This issue tracks according to a threshold the coverage reduction. What we want to check right there is we do not degrade the technical debt and so reduce the coverage compared to the previous status.

**Comment by re-schneider** [comment]
Code builds but some unit-tests are still failing...

**Comment by acopet** [comment]
Last change has broken the main flow of the plugin, hence the unit test results.
I am going to review the change to restore the expected flow.

**Comment by acopet** [comment]
**Conflicts and Unit test regressions have been fixed.**

However, CompleteITCase test has failed for jdk1.8.
>Failed tests: 
  CompleteITCase.basicTest:88 No requests exactly matched. Most similar request was:  expected:<
GET
/rest/api/1.0/users/myUser
User-Agent: Stash/[0-9]+
but was:<
GET
/rest/api/1.0/users/myUser
User-Agent: SonarQube/4.5.7 Stash/1.2.0-SNAPSHOT AHC/1.0

@t-8ch , could you please help?

Cheers,
Antoine

**Comment by re-schneider** [comment]
Thank you very much Antoine for the update of the branch. I was able to fix the unit-testing and now it s all green ! (yay !)

**Comment by re-schneider** [comment]
Replaced by PR# 89

**Pull request closed without merging**
