### PR TITLE
Update AsyncHttpClient from com.ning to org.asynchttpclient

### LINKED ISSUE #44: Unable to get SonarQube reviewer from Stash: java.util.concurrent.ExecutionException: java.net.ConnectException: https://agit.***.be:6088
When trying to get info from my BitBucket instance I get the following stack trace when running maven in debug mode.

```
[INFO] ANALYSIS SUCCESSFUL
[DEBUG] Post-jobs : org.******.plugins.stash.StashIssueReportingPostJob@79235a62
[INFO] Executing post-job org.******.plugins.stash.StashIssueReportingPostJob
[DEBUG] Trying to recover from failing to connect channel [id: 0x41d34189, /10.64.130.29:36896 :> agit.***.be/10.64.130.14:6088] with a retry value of true 
[DEBUG] Trying to recover request DefaultHttpRequest(chunked: false)
GET /rest/api/1.0/users/*** HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Host: agit.***.be:6088
Authorization: Basic ***wNjIwNTp5SGZPME42MEpocllTM0MxSHJKcw==
Accept: */*
User-Agent: AHC/1.0

[DEBUG] Channel Closed: [id: 0x41d34189, /10.64.130.29:36896 :> agit.***.be/10.64.130.14:6088] with attribute null
[DEBUG] Trying to recover from failing to connect channel [id: 0x3663691b, /10.64.130.29:36897 :> agit.***.be/10.64.130.14:6088] with a retry value of true 
[DEBUG] Trying to recover request DefaultHttpRequest(chunked: false)
GET /rest/api/1.0/users/*** HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Host: agit.***.be:6088
Authorization: Basic ***wNjIwNTp5SGZPME42MEpocllTM0MxSHJKcw==
Accept: */*
User-Agent: AHC/1.0

[DEBUG] Channel Closed: [id: 0x3663691b, /10.64.130.29:36897 :> agit.***.be/10.64.130.14:6088] with attribute null
[DEBUG] Trying to recover from failing to connect channel [id: 0xea7b0e95, /10.64.130.29:36898 :> agit.***.be/10.64.130.14:6088] with a retry value of true 
[DEBUG] Unable to recover future NettyResponseFuture{currentRetry=6,
  isDone=false,
  isCancelled=false,
  asyncHandler=com.ning.http.client.AsyncCompletionHandlerBase@418eef65,
  nettyRequest=com.ning.http.client.providers.netty.request.NettyRequest@45b1738c,
  content=null,
  uri=https://agit.***.be:6088/rest/api/1.0/users/***,
  keepAlive=true,
  httpHeaders=null,
  exEx=null,
  redirectCount=0,
  timeoutsHolder=null,
  inAuth=false,
  statusReceived=false,
  touch=866670679}

[DEBUG] Failed to recover from connect exception: java.nio.channels.ClosedChannelException with channel [id: 0xea7b0e95, /10.64.130.29:36898 :> agit.***.be/10.64.130.14:6088]
[DEBUG] https://agit.***.be:6088
[DEBUG] Channel Closed: [id: 0xea7b0e95, /10.64.130.29:36898 :> agit.***.be/10.64.130.14:6088] with attribute null
[ERROR] Unable to get SonarQube reviewer from Stash: java.util.concurrent.ExecutionException: java.net.ConnectException: https://agit.***.be:6088
[DEBUG] Exception stack trace
[ERROR] Process stopped: no SonarQube reviewer identified to publish to Stash the SQ analysis
```

### PR DESCRIPTION
**Pull request by bdhoine**
The com.ning client has a bug in the SSL context in some use cases.

Resolves #44

### CODE REVIEW

**Comment by widgetpl** [comment]
Hi i have tried this PR but i have some issues with redirections:

```
Request DefaultHttpRequest(chunked: false)
GET /rest/api/1.0/users/user HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Host: domain.name
Authorization: Basic
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://domain.name/rest/api/1.0/users/user
Connection: close
```

does it support redirections ? Our Stash instance is behind nginx

**Comment by bdhoine** [comment]
@widgetpl it seems that by default the library did not follow redirects indeed, I updated the PR, can you retest please? Thanks

**Comment by royteeuwen** [comment]
+1, Got the same problem

**Comment by mzielinski** [comment]
I changed version to 2.0.11 (this is the newest - in my fork), but problems seams to be resolved. Thanks for your contribution.  Great job !!!

**Comment by t-8ch** [comment]
@bdhoine @widgetpl @royteeuwen @mzielinski 

Sorry for the long delay, I am looking into it now.

Unfortunately we still support SonarQube versions which are compatible to Java 7 and as async-http-client > 2.0 is not, so I'd like to delay the migration to 2.0.

There are however newer versions for 1.X.X available than we are using.

So: Could you test again using version `1.9.39` of async-http-client? (Old groupId, ArtifactId, no code changes)

If the problem is fixed in this version we will use it as long as we still support Java 7.
Thanks!

**Comment by t-8ch** [comment]
@bdhoine Could you give me a link to the reported issue if you have one?

**Comment by bdhoine** [comment]
@t-8ch I tried that in the past to just update the artifact without changing the group id, but this still does not work. The com.ning variant is just the same as the new group id, I tried with latest com.ning but this did not do the job. 

I understand you may not want to drop Java7 yet because it's still supported.. But then I won't take a further look at this issue.

**Comment by t-8ch** [comment]
@bdhoine Good to now. Then we will have to drop java 7 compat as soon as possible. I'll ask around here when we can do this. I'll reopen the issue, as it is indeed an issue.

**Comment by t-8ch** [comment]
@bdhoine The plan is to cut a last release supporting SonarQube 4.5.7/Java 7 in the next two weeks, and then migrating to the new http client.

**Comment by t-8ch** [comment]
Could you tray again with the code from #67 ? This replaces the async-http-client with the one from stdlib, as we don't need the features of the async client

**Comment by bdhoine** [comment]
will compile and test this tomorrow! great job, thanks!

**Comment by StanKocken** [comment]
Any update on this? I'm having the same issue.

**Comment by t-8ch** [comment]
This has been implemented

**Comment by royteeuwen** [comment]
Hey @t-8ch ,

When will this be released?

Thanks!
Roy

**Comment by t-8ch** [comment]
Hi @royteeuwen this will be in 1.3.0, which is pending a few pull requests but should be soonish.

**Pull request closed without merging**
