### PR TITLE
Support multi-module multi-module projects with same level parent setup

### PR DESCRIPTION
**Pull request by kingoleg**
Use workingDir instead of projectBaseDir to support multi-module projects with same level parent setup

### CODE REVIEW

**Comment by t-8ch** [comment]
Hm, we should move away from autodetection if does not work time and time again.
I propose a sonar.stash.source.root property (which defaults to the basedir).

The basedir is also (exclusively) [used by the sonar-github](https://github.com/SonarSource/sonar-github/blob/305c912fd7ad1d75575eede60d3248a1b5b8ecd6/src/main/java/org/sonar/plugins/github/PullRequestProjectBuilder.java) plugin, which is written by sonarsource themselves. So I would like to debug the issue you are encountering further.

**Comment by kingoleg** [comment]
If sonar-github uses basedir it can be wrong. Let see what we need this dir info:
1. We use it to find the related path to query sonar for metrics
2. We use it to find the files related to this PR (actually, new files sonar checks with preview mode)
3. The related path in bitbucket PR diff view for files to comment

For 1 and 2 there are other option to get this info. For 3 - I don't know, how sonar-github works. Actually, we can get this info just to compare all file in PR diff with files to comment.

Regarding hardcode and sonar.stash.source.root property. We don't need it, as you always can change a working dir:

For example, it you can $mvn sonar:sonar -fmodule/pom.xml from /home/git/project working dir would be /home/git/project. If you run $mvn sonar:sonar -fpom.xml from /home/git/project/module - working dir would be /home/git/project/module.

The other good new - this fix breaks nothing and it is very simple. All is needed - clear documentation about this.

The other option I see here - do not use project base dir or working dir at all to calculate paths. But this is an other story.

**Comment by t-8ch** [comment]
I am also thinking about compatability.
If we change the default to the working directory we will break:

* Users who depend on the old behaviour
* Users whose runner/infrastructure does not allow them to change the directory

So by keeping the default for the source root the the projectbasedir we keep the compatability for current users and with the explicit propery they can change that.

(I recieved a bug report from one of our internal users about this just 15 minutes ago.
For example they would be unable to change the working dir but can additional properties.
In the end the property would be set by the CI system automatically)

For your 1) we use the componentId which we already receive from the sonar-plugin-api, so this should always work.

**Comment by kingoleg** [comment]
> would be unable to change the working dir 

Sorry, I cannot believe it. If can call a *.bat/*.sh file, you can set any working directory. 

And again, now the plugin works only for code layout there project base dir and working dir are the same, the dir where main pom.xml lives. So this change is backward compatible.

**Comment by t-8ch** [comment]
The user does not call a script. They set a flag `codequality: true` in the build configuration and provide a `sonar-project.properties` in their repository.

I am not sure why the plugin only works when project base dir == working dir.
(I never tested it otherwise, but the code never uses the working dir).

**Comment by kingoleg** [comment]
`codequality: true`

what is CI? how does it call sonar? I'm 95% sure the CI server allow to tune the way sonar is called.

**Comment by t-8ch** [comment]
This is a inhouse system which has sonarqube integrate. The developers activate the flag and then can use the configuration file to configure things. (Normally the configuration is not required)

(The sonar-scanner travis integration seems to work the same way: https://docs.travis-ci.com/user/sonarqube/)

**Comment by kingoleg** [comment]
Travis has 

```
script:
  # other script steps might be done before running the actual SonarQube analysis
```

I think it can be used to change working dir. Any way, working dir in travis - is a top level git repo dir. Something we need. No configuration required for travis.

Inhouse system, I am sure, use top level git dir as well.

**Comment by t-8ch** [comment]
@kingoleg
But someone may not use the top level git dir. And then we would have to introduce a dedicated configuration variable anyways.

**Comment by kingoleg** [comment]
@t-8ch You can always call mvn sonar:sonar with -f parameter from top level git dir.

If you want - you can introduce a parameter for top git dir for sonar runner/mvn launchers, that does not allow configure run dir (as you talk about your inner tool, but I don't believe). As for me - it is not needed.

**Comment by t-8ch** [comment]
@kingoleg
I will add the parameter. The default will stay with the projectBaseDir for now.
This will be changed in a 2.0 version of the plugin, to not break compatability unnecessary.
The documentation will mention this parameter as required.

**Comment by kingoleg** [comment]
Even if you change default to build dir it will not break compatibility. Because now the plugin support only the project where pom.xml lives in build dir and this build dir is git root.

build dir = projectBaseDir = git root

**Comment by t-8ch** [comment]
The maven runner is happy to run from any directory, as long as the path to the pom is provided.

**Comment by kingoleg** [comment]
Correct. But sonar-stash plugin cannot work if pom.xml is not places on git root

**Comment by t-8ch** [comment]
Yes, if the pom is not in the git root.
But the case where the pom is in the git root and the scanner is execute from a totally different directory works today.
By switching to the working dir for relative file paths this would break.

**Comment by t-8ch** [comment]
This should be fixed in the current master and 1.3

**Comment by dhruva1995** [comment]
Hey @t-8ch, @kingoleg, even I have a similar issue,

gitRepo/
gitRepo/Parent/pom.xml
gitRepo/Child1/pom.xml
gitRepo/Child2/pom.xml

can you please elaborate on how to fix this issue
When I run the below command from gitRepo
mvn sonar:sonar -Psonar -fParent/pom.xml

I am getting gitRepo/Child1 should be relative to project baseDir.

I can't copy the parent's pom to gitRepo can you please suggest a way, I tried but I couldn't get the above comments, can one of you please summarize the steps to follow to resolve this issue.

**Comment by t-8ch** [comment]
@dhruva1995 Did you specify `sonar.stash.repository.root`?

**Pull request closed without merging**
