### PR TITLE
Configure base dir

### PR DESCRIPTION
**Pull request by kirkor**
This PR resolves problem described in Issue #25

It's based on @Bavoen code. Due to his inactive, I've update code regarding comments in previous PR #41

Updated description how to proper configure plugin to work with this change can be found here: https://github.com/kirkor/sonar-stash-test-project

### CODE REVIEW

**Comment by t-8ch** [comment]
Thanks @kirkor !
After looking at this pull request, I somehow got the intuition, that we should be able to handle this automatically.
I am now looking for a way to do so.

**Comment by t-8ch** [comment]
What about
```properties
sonar.sources = src/
```
?

**Comment by kirkor** [comment]
Hi @t-8ch 
I think that this will not work. This meant to be parameter for source code location.

I've have this option set in different project with hybris (src/hybris/bin/custom) and this was not working :( 

Generally the critical part is here: ```SonarQubeCollector:49```
From full path to the file we are cutting beginning. 

For example,
full path to file, ```E:/Jenkins/workspace/CI03/src/lib/src/main/java/pl/com/bernas/sonar/stash/test/lib/DummyService.java```
when ```sonar.projectBaseDir=src/``` the result will be ```lib/src/main/java/pl/com/bernas/sonar/stash/test/lib/DummyService.java```

Maybe I will try to workaround this like fallow:
move ```sonar-project.properties``` from ```src/``` to root, then change ```sonar.modules=lib,webapp``` to ```sonar.modules=src/lib,src/webapp```

I will update you about the result.

**Comment by kirkor** [comment]
To make it works out of the box the fallowing configuration is needed:
```sonar-project.properties``` placed in the project root
```sonar.modules=src/lib,src/webapp```` with full path to modules

This PR and #41 can be closed. The issue #25 is nor relevant anymore.

**Pull request closed without merging**
