### PR TITLE
Use the http client from the standard library 

### PR DESCRIPTION
**Pull request by t-8ch**
It works with Java 7 and 8, is already present and hopefully fixes some issues

### CODE REVIEW

**Comment by bdhoine** [comment]
FYI: I'm testing this branch today, packaging succeeds but if I run the test suite this test fails locally:

CompleteITCase.org.sonar.plugins.stash.CompleteITCase

**Comment by t-8ch** [comment]
@bdhoine Could you post the error? It works for me and travis (It starts a SonarQube server, so if you already have one running it will collide on the ports.)

**Comment by re-schneider** [comment]
@t-8ch : is this PR still relevant now that there was a switch done in commit a65244e3ba8d1a4ae3949e8f25680ca9adee0478 ?

**Comment by StanKocken** [comment]
@re-schneider yes, I still have some issues with this version

**Pull request closed without merging**
