### PR TITLE
i19 - Make summary comment optional

### PR DESCRIPTION
**Pull request by christiangalsterer**

### CODE REVIEW

**Comment by christiangalsterer** [comment]
Hi,
any update on this? What are your views/plans to integrate this PR?

**Comment by acopet** [comment]
As I told you through #19, this PR will be a candidate for release 1.2.0.
Release 1.1.0 is planned to be delivered at the end of this month.

**Comment by nvillard** [comment]
Code for this PR is fine, to be rebased+merged for next release

**Comment by christiangalsterer** [comment]
Included in PR #24.

**Pull request closed without merging**
